name:Python Build
on: [push]
jobs:
  build_sdist_and_wheel:
    name: Build source distribution and wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build
        uses: OpenAstronomy/build-python-dist@v1
